### ISSUE TITLE
Zuev 2.3

### ISSUE THREAD

**Issue by sergadin** [sergadin/109-2020#1]
Функция simp хороша, но почему она получает две функции?
https://github.com/sergadin/109-2020/blob/44d0c5f50d911883846d39f28636b9e5aefc15dc/Zuev_KP/2.3/func.c#L6

Не хватает основной функции. Она не должна получать на вход n.  Но вместо этого получает *точность*. Значение n должно выбираться автоматически (правило Рунге).

И тестов, соответственно, больше. Правильные ответы можете получать в Wolfram Alpha, например. Будем считать, что у них правильно.

**Comment by sergadin** [comment]
Раз у файла Rogova_DR/2.2/inte.c отмечено два разработчика (contributors), то назначу эту задачу (Issue) еще одному пользователю.

**Comment by edinorogova** [comment]
Я делала ее сама, просто она не прикреплялась и я попросила Кирилла попробовать это сделать со своего компьютера.25.03.2020, 14:13, "Sergey Afonin" <notifications@github.com>:
Assigned #1 to @edinorogova.

**Comment by edinorogova** [comment]
Сергей Александрович, а что это за чат? Перенесете, пожалуйста, дедлайн? А в моей программе нужно что-то исправлять?25.03.2020, 14:17, "даша рогова" <dasha975@yandex.ru>:Я делала ее сама, просто она не прикреплялась и я попросила Кирилла попробовать это сделать со своего компьютера.25.03.2020, 14:13, "Sergey Afonin" <notifications@github.com>:
Assigned #1 to @edinorogova.

**Comment by sergadin** [comment]
Что мне не нравится:

1) Функция почему-то от двух аргументов

https://github.com/sergadin/109-2020/blob/b8f9bd07a76a43552d481578099f6f739be17e90/Zuev_KP/2.3/func.c#L16

2) Нет одной функции интегрирования.
В тесте вы вызываете две функции для того, чтобы получить значение интеграла. А если вызов второй функции по ошибке будет "плохим". Например, ошиблись со значением `k`?
Заведите одну функци. и внутри нее делайте что хотите.

3) Изменение управляющей переменной внутри цикла.
https://github.com/sergadin/109-2020/blob/b8f9bd07a76a43552d481578099f6f739be17e90/Zuev_KP/2.3/func.c#L43

Этого **никогда** не надо делать.

4) Функция `rung`.
В таком виде её не должно быть. Зачем возвращать `k`, да еще как `double`!, а потом еще раз вызывать `simp`?

5) Имена файлов.
Что такое func?

**Comment by edinorogova** [comment]
Сергей Александрович, я исправила. Посмотрите, пожалуйста?25.03.2020, 18:27, "Sergey Afonin" <notifications@github.com>:
Что мне не нравится:

Функция почему-то от двух аргументов

https://github.com/sergadin/109-2020/blob/b8f9bd07a76a43552d481578099f6f739be17e90/Zuev_KP/2.3/func.c#L16


Нет одной функции интегрирования.
В тесте вы вызываете две функции для того, чтобы получить значение интеграла. А если вызов второй функции по ошибке будет "плохим". Например, ошиблись со значением k?
Заведите одну функци. и внутри нее делайте что хотите.


Изменение управляющей переменной внутри цикла.
https://github.com/sergadin/109-2020/blob/b8f9bd07a76a43552d481578099f6f739be17e90/Zuev_KP/2.3/func.c#L43


Этого никогда не надо делать.


Функция rung.
В таком виде её не должно быть. Зачем возвращать k, да еще как double!, а потом еще раз вызывать simp?


Имена файлов.
Что такое func?
